### ISSUE TITLE
HTTP binding for the message.

### ISSUE THREAD

**Issue by giorgiozoppi** [eclipse-uprotocol/up-java#10]
Scope of this issue is to add the HTTP binding to the general protocol and new abstract interface https://github.com/CrowCpp/Crow. Crow has it is own vcpkg so it enough do a vcpkg install crow and it easy to use.

**Comment by stevenhartley** [comment]
Closing, this should be in up-spec project

**Comment by giorgiozoppi** [comment]
Yep. It is somet

> Closing, this should be in up-spec project

Yep.
