### ISSUE TITLE
Drop UAuthority id and IP

### ISSUE THREAD

**Issue by sophokles73** [eclipse-uprotocol/up-java#102]
Linking to https://github.com/eclipse-uprotocol/up-spec/issues/120

UAuthority's `id` property is [defined as a byte array](https://github.com/eclipse-uprotocol/up-spec/blob/8fcb37da046193599aa961a78f05af4eedb90025/up-core-api/uprotocol/uri.proto#L63) without any further assumptions regarding its semantics nor encoding.

However, the [ShortUriSerializer](https://github.com/eclipse-uprotocol/up-java/blob/90c3e1ed9b80ca03629b3ecba41f99fb3e2a5e69/src/main/java/org/eclipse/uprotocol/uri/serializer/ShortUriSerializer.java#L80) assumes that the bytes in the array actually represent a UTF8 encoded string.

IMHO we need to either change the type of the `UAuthority.id` property to `string` or change the encoding of the `id` in the URI short format to use e.g. base16 (hex).

**Comment by sophokles73** [comment]
@stevenhartley WDYT?

**Comment by sophokles73** [comment]
Or, as a third option: get rid of the `id` field altogether and simply use the `name` field instead.

**Comment by sophokles73** [comment]
You mean, in order to not be required to change the proto3 file in a non-backwards compatible way?

**Comment by stevenhartley** [comment]
Agree, moved this to https://github.com/eclipse-uprotocol/up-spec/issues/115 since we need to fix it there

**Comment by PLeVasseur** [comment]
Sorry, maybe I didn't explain myself well.

For Micro form we need either an `id` or `ip` and ideally in bytes for clarity since in the Micro form spec it specifies down to the byte and bit level where to put the fields from the `UUri`.

**Comment by sophokles73** [comment]
However, if the `id` in reality contains the UTF8 representation of a String, then how is it different from the `name`? When creating a micro URI from it, it would make no difference if I put in the UTF8 byte representation of the `name` value or put in the (UTF8) bytes from the `id`, or would it?

**Comment by stevenhartley** [comment]
Addressed by 1.5.8 work
