### ISSUE TITLE
Make UMessageBuilder immutable

### ISSUE THREAD

**Issue by tamarafischer** [eclipse-uprotocol/up-java#154]
UMessageBuilder should not hold data and actually can be an interface with static methods - that it actually has.
UMessageBuilder should have static methods that return an immutable object

**Comment by stevenhartley** [comment]
If its an interface with static methods, how can I set the optional attributes and add the withXXX() APIs?

**Comment by stevenhartley** [comment]
Per offline conversation we already support the intention by using UMessage that is immutable in the L1 API
