### ISSUE TITLE
InMemorySubscriber  should specify what version of the subscription protobuf it is working with

### ISSUE THREAD

**Issue by tamarafischer** [eclipse-uprotocol/up-java#155]
Currently we have version 2 and version 3 of the subscription protobuf.
version 2 is the one actually used, as of typing this issue. I am not sure who is using version 3.

InMemorySubscriber should specify the version or maybe have 2 versions of Subscriber, otherwise we might have problems understanding the payload.

**Comment by stevenhartley** [comment]
This is addressed by #148  and the PR #158 .
