### ISSUE TITLE
Possible issue with UUID Deserializer

### ISSUE THREAD

**Issue by matthewd0123** [eclipse-uprotocol/up-java#174]
Wanted to bring up a possible problem with the uuid deserializer in up-java, according to a up-tck test. Attaching the results of both python and java's results for this uuid_deserializer test, and up-java is failing. Something is happening with the deserializer where the msb of the uuid is being set differently in java than in python. Can someone with more knowledge of this method in java take a look and see if it's an issue?
![Screenshot 2024-07-31 112052](https://github.com/user-attachments/assets/9c627de1-540c-4c31-8171-e490ad93590b)
![Screenshot 2024-07-31 112038](https://github.com/user-attachments/assets/3abacf0c-5999-4b11-bf00-41d7741c1588)

**Comment by stevenhartley** [comment]
It looks like the printed number for lsb is greater than 2^63-1 so it cannot fit in a long that has a range of -2^63 to 2^63-1 and that is why you get the negative number from up-java that uses a long.

**Comment by matthewd0123** [comment]
Looks like root cause was discovered, closing for now
