### ISSUE TITLE
Add a method to extract the VIN from a UAuthroity

### ISSUE THREAD

**Issue by tamarafischer** [eclipse-uprotocol/up-java#56]
In Cloud Applications it is important to know what car an event arrived from.
This VIN information is encoded into the UAuthroity.
It would be very helpful to have a method like the in the legacy internal SDK:

    static Optional<String> extractVinFromUAuthority(UAuthority uAuthority) {
        if (uAuthority.isLocal()) {
            return Optional.empty();
        }
        return uAuthority.domain().flatMap(domain -> {
            final String[] parts = domain.split("[.]", 0);
            return parts.length == 0 ? Optional.empty() : Optional.of(parts[0]);
        });
    }

**Comment by stevenhartley** [comment]
Per discussions on other thread, we will go back to only name and we cannot extract specific information from the name as that would mean the specification would require the name MUST be a VIN but it doesn't have to be
