### ISSUE TITLE
Unexpected exception when isExpired is called

### ISSUE THREAD

**Issue by mishap4** [eclipse-uprotocol/up-java#61]
Optional field might be empty.

UAttributesValidator.java:
public ValidationResult isExpired(UAttributes uAttributes) {
        ...
        long delta = System.currentTimeMillis() - maybeTime.get();   <=== if optional is empty it will throw an exception
        ... 
}

**Comment by mishap4** [comment]
In my opinion, method with name isExpired should return boolean instead of ValidationResult.

**Comment by stevenhartley** [comment]
issue already fixed in another PR
