### ISSUE TITLE
Id size never checked in MicroUriSerializer serialize method

### ISSUE THREAD

**Issue by adienzel** [eclipse-uprotocol/up-java#76]
when we serialize the URI to micro, we must test the size of the Id string. since we hold uint_8 as the length we can set the string to max 255 characters and that's lead to max size of the URI.id in the micro serialized to be 256 characters max that is with the first 8 bytes can't be more than 256 + 8 = 264 total.
The code must check that when ID is set that the micro will not exceed this size.
and it will be clearer if the set of the id size and the id copy will be in the same if. 

Remove 
"           // Write the ID length if the type is ID
            if (type == AddressType.ID) {
                os.write(Uri.getAuthority().getId().size());
            }
 and add the ' os.write(Uri.getAuthority().getId().size());'
to the part that copy the id :
                else if (Uri.getAuthority().hasId()) {
                    os.write(Uri.getAuthority().getId().toByteArray());
                }
to be:  else if (Uri.getAuthority().hasId()) {
                   os.write(Uri.getAuthority().getId().size())
                    os.write(Uri.getAuthority().getId().toByteArray());
                }

**Comment by stevenhartley** [comment]
Keeping this ticket open to pull out validation from serializer per recommendations

**Comment by stevenhartley** [comment]
We Droped micro URI format from 1.5.8
