### ISSUE TITLE
UriValidator isRpcMethod() and isRpcResponse(): should check for equality instead of .contains()

### ISSUE THREAD

**Issue by AnotherDaniel** [eclipse-uprotocol/up-java#86]
According to the [spec](https://github.com/eclipse-uprotocol/up-spec/blob/main/basics/uri.adoc#3-validators), UriValidator methods isRpcMethod() and isRpcResponse() should check for equality of resource name and instance (should be 'rpc' and 'response', respectively).
The up-java implementation uses .contains() for this check, which is not quite up to spec.

**Comment by stevenhartley** [comment]
Folks, feel free to question the spec if you disagree with any of it...

**Comment by AnotherDaniel** [comment]
Wouldn't say this is about the spec, more about the java implementation? Like - do we want these methods to return true for method uris with name "warpcount" or instance names like "sensoresponset"?

In up-rust, we decided to do a strict equals-check at the moment, which is why I brought this up here to potentially get things consistent...

**Comment by stevenhartley** [comment]
Fair enough. It should be "rpc." in the name so if Java is not looking for this then it is a bug for me to fix :-).

**Comment by stevenhartley** [comment]
merged

**Comment by PLeVasseur** [comment]
@AnotherDaniel giving notice to other implementations. We love to see it. :rocket:  :rocket:  :rocket:  :rocket:
