### ISSUE TITLE
Traceparent is missed in CloudEventFactory.buildBaseCloudEvent

### ISSUE THREAD

**Issue by dddj698** [eclipse-uprotocol/up-java#87]
Traceparent from UCloudEventAttributes should be added to CloudEventBuilder if present. 
Also it's missed in UCloudEvent.fromMessage()

**Comment by dddj698** [comment]
@jefftindall  Thanks for taking this issue. However, the issue is not fully fixed, as mentioned in issue description,  traceparent is missed in UCloudEvent.fromMessage()

**Comment by stevenhartley** [comment]
@jefftindall please address. sorry @dddj698 didn't verify that point

**Comment by jefftindall** [comment]
It was a test! 😄  @dddj698 passed 🏆 

I have published a new PR after re-reading the issue in it's entirety.  Unit test updated as well.

**Comment by dddj698** [comment]
@jefftindall  thank you!

**Comment by stevenhartley** [comment]
Closing again :-)
