### ISSUE TITLE
Supporting clarification that Uris should fit within the bits and bytes allocated for Micro Form when serializing

### ISSUE THREAD

**Issue by PLeVasseur** [eclipse-uprotocol/up-java#94]
Howdy folks :wave: 

Left a comment over on [this in-flight PR updating to support 1.5.7](https://github.com/eclipse-uprotocol/up-java/pull/88#issuecomment-1992275278), but surfacing as an issue as well for the attention :slightly_smiling_face:

**Comment by stevenhartley** [comment]
As Peter reported, there are still a few issues with the micro URI. Given that we are going to drop the id and ip from uAuthority, I'll fix up the rest of the micro issues then.
